packages:
  # all packages in direct sub dirs of packages/ and apps/
  - "packages/*"
  - "apps/*"
  # all packages in sub dirs of components/
  - "components/**"
  # exclude packages that are inside test directories
  - "!**/test/**"
